package raven.form;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import raven.tabbed.TabbedForm;
import raven.utils.JDBC;
import raven.utils.Model_Tour;

/**
 *
 * @author RAVEN
 */
public class DanhSachTour extends TabbedForm {

    /**
     * Creates new form TestForm
     */
    public DanhSachTour() {
        initComponents();
        init(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTimKiem = new javax.swing.JTextField();
        btnSerch = new javax.swing.JButton();
        btnReloadData = new javax.swing.JButton();
        btnXoaTour = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTour = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        btnSerch.setText("Serch");
        btnSerch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSerchActionPerformed(evt);
            }
        });

        btnReloadData.setText("ReLoadData");
        btnReloadData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReloadDataActionPerformed(evt);
            }
        });

        btnXoaTour.setText("Xóa Tour");
        btnXoaTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTourActionPerformed(evt);
            }
        });

        tblTour.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "MaTour", "TenTour", "DiaDiem", "SoNgay", "SoDem", "SoNguoi", "MoTa"
            }
        ));
        tblTour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTourMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTour);

        jLabel1.setText("Tìm Kiếm: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnXoaTour)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSerch)
                                .addGap(18, 18, 18)
                                .addComponent(btnReloadData)))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSerch, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReloadData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoaTour)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSerchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSerchActionPerformed
//        Serch();
    }//GEN-LAST:event_btnSerchActionPerformed

    private void btnReloadDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReloadDataActionPerformed
//        reload();
    }//GEN-LAST:event_btnReloadDataActionPerformed

    private void btnXoaTourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTourActionPerformed
//        xoaTour();
    }//GEN-LAST:event_btnXoaTourActionPerformed

    private void tblTourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTourMouseClicked

    }//GEN-LAST:event_tblTourMouseClicked

    @Override
    public boolean formClose() {
//       if(txt.getText().trim().equals("")){
//           return true;
//       }
       int opt=JOptionPane.showConfirmDialog(this, "Data not save do you want to close ?", "Close", JOptionPane.YES_NO_OPTION);
       return opt==JOptionPane.YES_OPTION;
    }

    @Override
    public void formOpen() {
        System.out.println("Form open");
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReloadData;
    private javax.swing.JButton btnSerch;
    private javax.swing.JButton btnXoaTour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTour;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables


     ArrayList<Model_Tour> list = new ArrayList<>();
    int current = 0;
    
    void init(){
        try {
            JDBC.getJdbc().connectToDatabase();
            load_data();
        } catch (Exception e) {
        }
    }
    
    
    public void load_data() throws SQLException{
        try {
            PreparedStatement ps = JDBC.getJdbc().getConnection().prepareStatement("Select * from Tour");
            ResultSet rs = ps.executeQuery();
            //1.Xoa cac doi tuong trong list
            list.clear();
            while (rs.next()) {
                //2. Tao 1 doi tuong Tour
                Model_Tour tour = new Model_Tour();
                //3. gan du lieu vao
                tour.setMaTour(rs.getString("MaTour"));
                tour.setTenTour(rs.getString("TenTour"));
                tour.setDiaDiem(rs.getString("DiaDiem"));
                tour.setSoNgay(rs.getString("SoNgay"));
                tour.setSoDem(rs.getString("SoDem"));
                tour.setSoNguoi(rs.getString("SoNguoi"));
                tour.setMoTa(rs.getString("MoTa"));
                //Them gra vao list
                list.add(tour);

            }
            DefaultTableModel model = (DefaultTableModel) tblTour.getModel();
            model.setRowCount(0);
            for (Model_Tour tour : list) {
                Object[] row = new Object[]{tour.getMaTour(), tour.getTenTour(), tour.getDiaDiem(), tour.getSoNgay(), tour.getSoDem(), tour.getSoNguoi(), tour.getMoTa()};
                model.addRow(row);
            }
            rs.close();
            ps.close();
        } catch (Exception e) {
        }
    }
}
